# Training hyperparameters
LEARNING_RATE = 0.001
BATCH_SIZE = 256 
EPOCHS = 10

# Model hyperparameters
IMAGE_SIZE = 56
PATCH_SIZE = 14
NUM_PATCHES = IMAGE_SIZE ** 2 // PATCH_SIZE ** 2
DIGITS = 1
EMBEDDING_DIM = 64
LATENT_DIM = 32
ENCODER_ATTENTION_BLOCKS = 3
DECODER_ATTENTION_BLOCKS = 4