# Training hyperparameters
LEARNING_RATE = 0.001
BATCH_SIZE = 128 
EPOCHS = 10

# Model hyperparameters
IMAGE_SIZE = 56
PATCH_SIZE = 14
NUM_PATCHES = IMAGE_SIZE ** 2 // PATCH_SIZE ** 2
EMBEDDING_DIM = 64
LATENT_DIM = 128
ENCODER_ATTENTION_BLOCKS = 10
DECODER_ATTENTION_BLOCKS = 10